# Warning: The database defined as "test" will be erased when you run "rake".
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: scirate_dev
  pool: 5
  username: kevinz

production:
  adapter: postgresql
  encoding: unicode
  database: scirate
  pool: 5
  username: kevinz
